version: "2"

services:
 stalkphish_oss:
  image: stalkphish-oss
  container_name: stalkphish-oss
  hostname: stalkphish-oss
  build:
      context: ../
      dockerfile: docker/Dockerfile
  volumes:
   - /tmp/log:/opt/StalkPhish/stalkphish/log:rw
   - /tmp/dl:/opt/StalkPhish/stalkphish/dl:rw
   - /tmp/db:/opt/StalkPhish/stalkphish/db:rw
  command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
